### PR TITLE
Allow scp106 to pass through door

### PR DESCRIPTION
**Pull request by M60TM**
- I think [line 3332 in scp_sf.sp](https://github.com/redsunservers/SCP-Secret-Fortress/blob/master/addons/sourcemod/scripting/scp_sf.sp#L3332) is Collision Hook's forward and it used for doorwalk.
- Maybe it used for same purpose like this pull request. But I don't know why that code is disabled.
- This pull request might be require to rebalance scp106, because passing through door is very useful to chasing player.

### CODE REVIEW

**Review by FortyTwoFortyTwo — CHANGES_REQUESTED** [review]
May well then remove `CH_ShouldCollide` if it's unusued. Also could remove `OnDoorTouch` and just use this detour to keep it simpler?

Now would this allow scp106 able to walk though an elevator door? Should prevent them able to do so. (see `FixUpDoors` and `DestroyOrOpenDoor`)

As for balance wise, I don't have much suggestions on what to nerf it.

**Comment by M60TM** [comment]
Now using `Classes_OnDoorWalk` to block to pass through the elevator door. In this way, 076, 096 and spec will use this detour, but I'm not sure if we can remove `OnDoorTouch`.

**Comment by FortyTwoFortyTwo** [comment]
Okay I had to do several changes to make it work well. Full changes include:
- Splitting up `func_doorwalk` and `func_doortouch` to ensure door is actually being touched to break it.
- SCP-106 can walk though any doors, except elevators
- Remove extra keycard access for SCP-076, SCP-096 and SCP-106
- Consistency fixes between func_door, func_movelinear and each maps

Needs testing

**Review by FortyTwoFortyTwo — APPROVED** [review]
seems to work fine

**Pull request merged**
