### PR TITLE
Change win condition

### PR DESCRIPTION
**Pull request by M60TM**
- Captured sci/d-class is now considered to d-class/sci
- Nerfed SCP-035's health
- Changed SCP-035's crossvec to COM-18 and machete

+ yeah. Redsun is different. Their player can't kill easily SCP-035, so I nerfed him.

### CODE REVIEW

**Comment by Mikusch** [comment]
I feel like nerfing the health of SCP-035 (especially to a value as low as 200) is a bit extreme and would just make him extremely fragile. I think it's fine to adjust his starting loadout and leave it at that.

**Comment by M60TM** [comment]
I'll take your opinion. And I fixed the bug where the SCP-173's puddle slowed down the spectator.

**Comment by FortyTwoFortyTwo** [comment]
> Captured sci/d-class is now considered to d-class/sci

Is there a reason behind this? I somewhat prefer having current winning condition, unless if there an actual reason behind this change.

**Comment by M60TM** [comment]
> It is intended to encourage arrest. And later when someone escapes, when opposing support comes (chaos insurgency wave with only scientists left), arrest is meaningless and only kills them for quick game progression.

**Comment by M60TM** [comment]
> > Captured sci/d-class is now considered to d-class/sci
> 
> Is there a reason behind this? I somewhat prefer having current winning condition, unless if there an actual reason behind this change.

It is intended to encourage arrest. And later when someone escapes, when opposing support comes (chaos insurgency wave with only scientists left), arrest is meaningless and only kills them for quick game progression.

**Comment by Mikusch** [comment]
I'm not sure I quite understand the win condition change, could you elaborate? How does it work now?

**Comment by M60TM** [comment]
disarmed/captured escapes count as one score just like normal escapes, instead of captured escapes only being a tie breaker.

**Review by Mikusch — APPROVED** [review]

**Comment by FortyTwoFortyTwo** [comment]
While the code looks fine, I'm still not in favour of this win condition change.

> It is intended to encourage arrest. And later when someone escapes, when opposing support comes (chaos insurgency wave with only scientists left), arrest is meaningless and only kills them for quick game progression.

If anything, we actually want a quick game on a lengthily gamemode, but that is just my thoughts.

**Comment by woisalreadytaken** [comment]
> If anything, we actually want a quick game on a lengthily gamemode, but that is just my thoughts.

I guess it depends where the gamemode is being played

For multi-gamemode servers it is probably ideal to have faster games yeah, but for 24/7 SCP servers, I can see people being completely fine with longer games.

My opinion is that I wouldn't mind trying this out and see how it goes, could maybe even turn this into a convar for some sort of middle ground.

**Comment by M60TM** [comment]
> While the code looks fine, I'm still not in favour of this win condition change.
> If anything, we actually want a quick game on a lengthily gamemode, but that is just my thoughts.

After months of testing, I knew it didn't take so long. 
However, since the average round time at redsun was longer than the server I tested, it remains to be seen what effect it will have.

**Comment by M60TM** [comment]
> I guess it depends where the gamemode is being played
> 
> For multi-gamemode servers it is probably ideal to have faster games yeah, but for 24/7 SCP servers, I can see people being completely fine with longer games.
> 
> My opinion is that I wouldn't mind trying this out and see how it goes, could maybe even turn this into a convar for some sort of middle ground.

actually..It can control in gamemode.cfg and map's own config(ex. scp_abandoned.cfg).
Then, I can go in the direction of creating a new win condition, such as conditionclassic(old sl rule).

**Comment by woisalreadytaken** [comment]
> actually..It can control in gamemode.cfg and map's own config(ex. scp_abandoned.cfg).
> Then, I can go in the direction of creating a new win condition, such as conditionclassic(old sl rule).

oh, didn't know that, that's cool
then yeah I'd personally like having the option to choose, but I have no authority here I'm just sharing a thought, dunno about everyone

**Comment by Mikusch** [comment]
Yeah, I think I would prefer that being configurable.

**Comment by M60TM** [comment]
The existing winning conditions were maintained. Instead, what I was going to change was renamed VipAlt, and I added SlNew, another win condition. SlNew is tweaked version of scp-sl's game rule, without an auto-nuke, a game would take a long time. Auto-nuke can added by editing map's logic_auto.

**Comment by Mikusch** [comment]
Have not tested the new win conditions, but looks good to me.

**Review by FortyTwoFortyTwo — APPROVED** [review]
`Gamemode_ConditionVipAlt` Could be updated where in case of a tie between sci and dbois (both escapes and captured), then check which team has the most escapes without captures counted, otherwise this should be good anyway.

**Pull request merged**
